### ISSUE TITLE
Document what permissions are needed?

### ISSUE THREAD

**Issue by hobbes1069** [jordantrizz/mikrotik-scripts#1]
Thank you very much for the scripts! After my SOHO netgear router bit the dust I decided to try a MikroTik cloud router switch and until now did not have dyndns updates automated.

Either in a traditional INSTALL file or in comments in the script could you document the permissions each script needs? I always try to run everything with the minimal level of permissions.

**Comment by jordantrizz** [comment]
To be perfectly honest I use the default, "ftp,reboot,read,write,policy,test,password,sniff,sensitive" and could be locked down further. For instance it wouldn't need reboot, policy, or password access.

**Comment by hobbes1069** [comment]
Ok, thanks! This is my first Mikrotik router/switch so I'm still learning a lot (some of it the hard way).
